<div class="row">
    <div class="center" >
        <div class="col-md-2">
            <p class="lead">Products-Pilot</p>
            <div class="list-group">
                <?php foreach($this->categories as $i => $category) { ?>
                    <a href="#" class="list-group-item"> <?php echo $category->name ?> </a>
                <?php } ?>
            </div>
        </div>

        <div class="col-md-8">

            <div class="row carousel-holder">

                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>



            <div class="row">
                <?php foreach($this->products as $i => $product) { ?>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img class = "thumbnail" src="<?php echo '/uploads/images/' . $product->image ?>" alt="">
                            <div class="caption">
                                <h4 class="pull-right">$ <?php echo number_format((float)$product->price,2,',','.') ?> </h4>
                                <h4><a href="<?php echo  $this->url(array('controller' => 'products','action' => 'view', 'id' => $product->id), null, true);?> "><?php echo $product->name ?></a> </h4>
                                <p><?php echo substr($product->description,0,80) ?></p>
                                <p>Attached file:
                                    <?php if($product->file) { ?>
                                        <a href="<?php  echo '/uploads/data/' . $product->file;?>" download> <?php echo $product->file;?> </a>
                                    <?php } else { ?>
                                        -Not Found-
                                    <?php } ?>
                                </p>
                            </div>

                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>

                            <div class="bybutton">
                                <a href="#"><img src="/img/add_to_cart.jpg" onclick="addToCart('<?php echo 'email' ?>','<?php echo $product->id ?>')"></a>
                            </div>
                        </div>
                    </div>

                <?php } ?>
            </div>
        </div>
    </div>
</div>