<div class="row">
    <div class="center" >
        <div class="col-md-2">
            <p class="lead">Products-Pilot</p>
            <div class="list-group">
                <?php foreach($this->categories as $i => $category) { ?>
                    <a href="#" class="list-group-item"> <?php echo $category->name ?> </a>
                <?php } ?>
            </div>
        </div>

        <div class="col-md-8">

            <div class="thumbnail">
                <img class=" item img-responsive" src="<?php echo '/uploads/images/' . $this->product->image ?>" alt="">
                <div class="caption-full">
                    <h4 class="pull-right">$ <?php echo number_format((float)$this->product->price,2,',','.') ?></h4>
                    <h4><a href="#"><?php echo $this->product->name ?></a></h4>
                    <p><?php echo substr($this->product->description,0,80) ?></p>
                    <p>Attached file:
                        <?php if($this->product->file) { ?>
                            <a href="<?php  echo '/uploads/data/' . $this->product->file;?>" download> <?php echo $this->product->file;?> </a>
                        <?php } else { ?>
                            -Not Found-
                        <?php } ?>
                    </p>
                </div>
                <div class="ratings">
                    <p class="pull-right">3 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                        4.0 stars
                    </p>
                </div>
                <div class="bybutton">
                    <a href="#"><img src="/img/add_to_cart.jpg" onclick="addToCart('<?php echo 'email' ?>','<?php echo $this->product->id ?>')"></a>
                </div>
            </div>
        </div>
    </div>
</div>